import uuid
from decimal import Decimal, InvalidOperation

from fastapi import APIRouter, Depends, HTTPException, Query, status
from sqlalchemy import and_, func, or_
from sqlalchemy.orm import Session, joinedload, selectinload

from app.db.session import get_db
from app.db import models
from app.api import schemas
from app.api.deps import get_current_user
from app.adapters.auth.base import AuthenticatedUser
from app.domain import material_consumption_service as svc
from app.domain.pallet_serialization import serialize_mc_detail, serialize_mc_list_item

router = APIRouter(prefix="/api/v1/material-consumption", tags=["material-consumption"])

MODULE = "material_consumption"

SHIFTS = ["Shift A", "Shift B", "Shift C"]


def get_perms(current_user: AuthenticatedUser = Depends(get_current_user), db: Session = Depends(get_db)) -> models.ModulePermission:
    perm = db.query(models.ModulePermission).filter(models.ModulePermission.user_id == current_user.user_id, models.ModulePermission.module == MODULE).first()
    if not perm:
        perm = models.ModulePermission(user_id=current_user.user_id, module=MODULE, can_view=True)
    return perm


def require(action: str):
    def _dep(perm: models.ModulePermission = Depends(get_perms)):
        if not getattr(perm, f"can_{action}", False):
            raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail=f"You do not have permission to {action} this record.")
        return perm
    return _dep


def _q(db: Session):
    return (
        db.query(models.MaterialConsumption)
        .options(
            joinedload(models.MaterialConsumption.machine_entries)
            .joinedload(models.MaterialConsumptionMachineEntry.pallets)
            .joinedload(models.MaterialConsumptionPallet.pallet),
            joinedload(models.MaterialConsumption.machine_entries)
            .joinedload(models.MaterialConsumptionMachineEntry.machine),
            joinedload(models.MaterialConsumption.production_run).joinedload(models.ProductionRun.ipqc_record),
        )
    )


def _q_for_list(db: Session):
    """Same shape as `_q()`'s eager-loaded relationships, but with the
    one-to-many collections loaded via `selectinload` (separate `IN (...)`
    queries) instead of `joinedload` (a single row-fanout join). For a page
    of ~50 parent rows this avoids the join exploding into thousands of raw
    rows that SQLAlchemy's identity map then has to collapse back down --
    the fix for finding #1 in PERF_AUDIT.md. Only ever called on an
    already-paginated id set, never on the full table."""
    return (
        db.query(models.MaterialConsumption)
        .options(
            selectinload(models.MaterialConsumption.machine_entries)
            .selectinload(models.MaterialConsumptionMachineEntry.pallets)
            .joinedload(models.MaterialConsumptionPallet.pallet),
            selectinload(models.MaterialConsumption.machine_entries)
            .joinedload(models.MaterialConsumptionMachineEntry.machine),
            joinedload(models.MaterialConsumption.production_run).joinedload(models.ProductionRun.ipqc_record),
        )
    )


def _filtered_mc_query(db: Session, search: str, category: str, date: str, status_: str):
    """Builds the WHERE clause entirely in SQL (search spans machine_entries/
    machines/pallets via correlated EXISTS subqueries generated by
    `.any()`/`.has()`) instead of the old pattern of fetching every row and
    filtering in Python."""
    q = db.query(models.MaterialConsumption.id)
    if status_:
        q = q.filter(models.MaterialConsumption.status == status_)
    if date:
        q = q.filter(models.MaterialConsumption.consumption_date == date)
    if category:
        q = q.filter(models.MaterialConsumption.machine_entries.any(models.MaterialConsumptionMachineEntry.category == category))
    if search:
        like = f"%{search.lower()}%"
        entry_matches = or_(
            func.lower(models.MaterialConsumptionMachineEntry.sku_code_snapshot).like(like),
            func.lower(models.MaterialConsumptionMachineEntry.sku_version_snapshot).like(like),
            func.lower(models.MaterialConsumptionMachineEntry.category).like(like),
            models.MaterialConsumptionMachineEntry.machine.has(func.lower(models.Machine.code).like(like)),
            models.MaterialConsumptionMachineEntry.pallets.any(
                and_(
                    models.MaterialConsumptionPallet.role == "primary",
                    models.MaterialConsumptionPallet.pallet.has(func.lower(models.Pallet.display_id).like(like)),
                )
            ),
        )
        q = q.filter(models.MaterialConsumption.machine_entries.any(entry_matches))
    return q


def _get_or_404(db: Session, mc_id: uuid.UUID) -> models.MaterialConsumption:
    mc = _q(db).filter(models.MaterialConsumption.id == mc_id).first()
    if not mc:
        raise HTTPException(status_code=404, detail="Material Consumption record not found")
    return mc


def _get_entry_or_404(mc: models.MaterialConsumption, entry_id: uuid.UUID) -> models.MaterialConsumptionMachineEntry:
    entry = next((e for e in mc.machine_entries if e.id == entry_id), None)
    if not entry:
        raise HTTPException(status_code=404, detail="Machine entry not found on this record")
    return entry


@router.get("/shifts", response_model=list[str])
def list_shifts(_perm=Depends(require("view"))):
    return SHIFTS


@router.get("")
def list_material_consumption(
    search: str = Query(""), category: str = Query(""), date: str = Query(""), status_: str = Query("", alias="status"),
    page: int = Query(default=1, ge=1), page_size: int = Query(default=50, ge=1, le=200),
    db: Session = Depends(get_db), _perm=Depends(require("view")),
):
    filtered = _filtered_mc_query(db, search, category, date, status_)
    total_all = db.query(func.count(models.MaterialConsumption.id)).scalar()
    # When no filter is active, `filtered` is equivalent to the unfiltered
    # query, so matched_count == total_count by construction -- skip the
    # second COUNT round trip for the common no-filter (default list load)
    # case. Any active filter still runs its own COUNT, since the two can
    # genuinely differ.
    matched = total_all if not (search or category or date or status_) else filtered.count()
    page_ids = [
        row[0]
        for row in filtered.order_by(models.MaterialConsumption.created_at.desc())
        .offset((page - 1) * page_size)
        .limit(page_size)
        .all()
    ]
    recs_by_id = {}
    if page_ids:
        recs_by_id = {r.id: r for r in _q_for_list(db).filter(models.MaterialConsumption.id.in_(page_ids)).all()}
    items = [serialize_mc_list_item(recs_by_id[i]) for i in page_ids if i in recs_by_id]
    return {"items": items, "matched_count": matched, "total_count": total_all}


@router.post("/draft", response_model=schemas.MaterialConsumptionDetailOut, status_code=201)
def create_draft(
    db: Session = Depends(get_db),
    current_user: AuthenticatedUser = Depends(get_current_user),
    _perm=Depends(require("create")),
):
    import datetime as _dt
    mc = models.MaterialConsumption(
        consumption_date=_dt.date.today().isoformat(), status="draft", created_by=current_user.user_id,
    )
    db.add(mc)
    db.flush()
    # Every record starts with one (empty) machine slot -- Page 1 always has
    # at least one machine to fill in; "+ Add Machine" adds more.
    db.add(models.MaterialConsumptionMachineEntry(material_consumption_id=mc.id, sort_order=0))
    db.commit()
    return serialize_mc_detail(_get_or_404(db, mc.id))


@router.get("/{mc_id}", response_model=schemas.MaterialConsumptionDetailOut)
def get_material_consumption(mc_id: uuid.UUID, db: Session = Depends(get_db), _perm=Depends(require("view"))):
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.put("/{mc_id}/basic", response_model=schemas.MaterialConsumptionDetailOut)
def update_basic(
    mc_id: uuid.UUID, payload: schemas.MaterialConsumptionBasicUpdate,
    db: Session = Depends(get_db), current_user: AuthenticatedUser = Depends(get_current_user),
    _perm=Depends(require("edit")),
):
    mc = _get_or_404(db, mc_id)
    if mc.status != "draft":
        raise HTTPException(status_code=422, detail="This Material Consumption record has already been saved and cannot be changed.")
    if payload.shift is not None:
        mc.shift = payload.shift or None
    mc.updated_by = current_user.user_id
    db.commit()
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.post("/{mc_id}/machine-entries", response_model=schemas.MaterialConsumptionDetailOut, status_code=201)
def add_machine_entry(
    mc_id: uuid.UUID, body: schemas.MaterialConsumptionMachineEntryIn,
    db: Session = Depends(get_db), _perm=Depends(require("create")),
):
    mc = _get_or_404(db, mc_id)
    try:
        svc.add_machine_entry(db, mc, machine_id=body.machine_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.delete("/{mc_id}/machine-entries/{entry_id}", response_model=schemas.MaterialConsumptionDetailOut)
def remove_machine_entry(
    mc_id: uuid.UUID, entry_id: uuid.UUID,
    db: Session = Depends(get_db), _perm=Depends(require("edit")),
):
    mc = _get_or_404(db, mc_id)
    try:
        svc.remove_machine_entry(db, mc, entry_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.put("/{mc_id}/machine-entries/{entry_id}", response_model=schemas.MaterialConsumptionDetailOut)
def update_machine_entry(
    mc_id: uuid.UUID, entry_id: uuid.UUID, body: schemas.MaterialConsumptionMachineEntryIn,
    db: Session = Depends(get_db), _perm=Depends(require("edit")),
):
    mc = _get_or_404(db, mc_id)
    entry = _get_entry_or_404(mc, entry_id)
    try:
        svc.set_machine_entry_machine(db, mc, entry, body.machine_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.post("/{mc_id}/machine-entries/{entry_id}/scan-pallet", response_model=schemas.MaterialConsumptionDetailOut)
def scan_pallet(
    mc_id: uuid.UUID, entry_id: uuid.UUID, body: schemas.MaterialConsumptionScanIn,
    db: Session = Depends(get_db), current_user: AuthenticatedUser = Depends(get_current_user),
    _perm=Depends(require("create")),
):
    mc = _get_or_404(db, mc_id)
    entry = _get_entry_or_404(mc, entry_id)
    try:
        svc.add_primary_pallet(db, mc, entry, body.payload, client_time=body.client_time, actor_user_id=current_user.user_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.post("/{mc_id}/machine-entries/{entry_id}/scan-secondary", response_model=schemas.MaterialConsumptionDetailOut)
def scan_secondary(
    mc_id: uuid.UUID, entry_id: uuid.UUID, body: schemas.MaterialConsumptionSecondaryScanIn,
    db: Session = Depends(get_db), _perm=Depends(require("create")),
):
    mc = _get_or_404(db, mc_id)
    entry = _get_entry_or_404(mc, entry_id)
    try:
        svc.add_secondary_pallet(db, mc, entry, body.payload, body.category)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.delete("/{mc_id}/pallets/{row_id}", response_model=schemas.MaterialConsumptionDetailOut)
def remove_pallet(
    mc_id: uuid.UUID, row_id: uuid.UUID,
    db: Session = Depends(get_db), _perm=Depends(require("edit")),
):
    mc = _get_or_404(db, mc_id)
    try:
        svc.remove_pallet(db, mc, row_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


class QuantityIn(schemas.BaseModel):
    quantity: str


@router.put("/{mc_id}/pallets/{row_id}/quantity", response_model=schemas.MaterialConsumptionDetailOut)
def set_pallet_quantity(
    mc_id: uuid.UUID, row_id: uuid.UUID, body: QuantityIn,
    db: Session = Depends(get_db), _perm=Depends(require("edit")),
):
    mc = _get_or_404(db, mc_id)
    try:
        qty = Decimal(body.quantity)
    except (InvalidOperation, ValueError):
        raise HTTPException(status_code=422, detail="Invalid quantity.")
    try:
        svc.set_secondary_quantity(db, mc, row_id, qty)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.post("/{mc_id}/save-draft", response_model=schemas.MaterialConsumptionDetailOut)
def save_draft(mc_id: uuid.UUID, db: Session = Depends(get_db), _perm=Depends(require("create"))):
    """Draft is already persisted as records are scanned/edited -- this
    endpoint exists purely to mirror the app's Save-Draft-vs-Submit UX
    convention. It intentionally does nothing beyond confirming the record
    exists: no pallet is consumed, no Production Run/IPQC is created."""
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.post("/{mc_id}/finalize", response_model=schemas.MaterialConsumptionDetailOut)
def finalize(
    mc_id: uuid.UUID, db: Session = Depends(get_db),
    current_user: AuthenticatedUser = Depends(get_current_user),
    _perm=Depends(require("create")),
):
    mc = _get_or_404(db, mc_id)
    try:
        svc.finalize(db, mc, actor_user_id=current_user.user_id)
        db.commit()
    except svc.MaterialConsumptionError as e:
        db.rollback()
        raise HTTPException(status_code=422, detail=e.message)
    return serialize_mc_detail(_get_or_404(db, mc_id))


@router.delete("/{mc_id}/if-blank", status_code=204)
def discard_if_blank(mc_id: uuid.UUID, db: Session = Depends(get_db)):
    mc = (
        db.query(models.MaterialConsumption)
        .options(
            joinedload(models.MaterialConsumption.machine_entries).joinedload(models.MaterialConsumptionMachineEntry.pallets)
        )
        .filter(models.MaterialConsumption.id == mc_id)
        .first()
    )
    if mc and mc.status == "draft" and svc.is_blank(mc):
        db.delete(mc)
        db.commit()
    return None


@router.delete("/{mc_id}")
def delete_material_consumption(mc_id: uuid.UUID, db: Session = Depends(get_db), _perm=Depends(require("delete"))):
    mc = _get_or_404(db, mc_id)
    blocked = svc.find_dependent_summary(mc)
    if blocked:
        raise HTTPException(status_code=409, detail=blocked)
    db.delete(mc)
    db.commit()
    return {"ok": True}
